ARG NODE_VERSION=21.6.0
FROM node:${NODE_VERSION}-slim as base

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl procps

COPY package.json .

COPY . .

RUN corepack enable

RUN corepack prepare pnpm@latest --activate

RUN pnpm install

CMD ["pnpm", "run", "start:dev"]