FROM node:slim

WORKDIR app

RUN apt-get update -y && apt-get install -y openssl

COPY package.json .

COPY . .

RUN corepack enable

RUN corepack prepare pnpm@latest --activate

RUN pnpm install

CMD ["pnpm", "run", "start:dev"]