version: '3.7'


services:
  application:
    volumes:
      - .:/app
    build: 
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    restart: always
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - NOTION_AUTH_TOKEN=${NOTION_AUTH_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - TELEGRAM_NOTIFICATION_BOT=${TELEGRAM_NOTIFICATION_BOT}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    

