version: '3.7'

services:
  application:
    ports:
      - "3000:8080"
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    env_file:
      - .env