version: '3.7'

services:
  application:
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    env_file:
      - .env