services:
  api:
    volumes:
      - ./src/:/app/src
      - ./prisma/schema.prisma/:/app/prisma/schema.prisma
    build:
      context: .
      dockerfile: "./docker/dev/dockerfile"
    container_name: okami
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  broker:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"


