version: '3.7'

services:
  api:
    volumes:
      - ./src/:/app/src
      - /app/node_modules
    build: 
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env


