version: '3.7'

services:
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - webapp
    volumes:
      - ./prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - okami_network


  application:
    depends_on:
      - proxy
    hostname: okami
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    networks:
      - okami_network
    env_file:
      - .env


networks:
  okami_network:
