version: '3.7'

services:
  application:
    build: 
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - NOTION_AUTH_TOKEN=${NOTION_AUTH_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - TELEGRAM_NOTIFICATION_BOT=${TELEGRAM_NOTIFICATION_BOT}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - PORT=${PORT}
      - ADDRESS=${ADDRESS}
  es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        container_name: es01
        volumes:
          -  ./data/es01:/var/lib/elasticsearch/data
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1

                
 
        ports:
            - 9200:9200
  kibana:
        image: docker.elastic.co/kibana/kibana:7.11.2
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    

