version: '3.7'

services:
  api:
    volumes:
      - ./src/:/app/src
      - ./prisma/schema.prisma/:/app/prisma/schema.prisma
    build: 
      context: .
      dockerfile: "./docker/dev/dockerfile"
    container_name: okami
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

