version: '3.7'

services:
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - application
    volumes:
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      -  ./src/:/app/src
      - ./prisma/schema.prisma/:/app/prisma/schema.prisma
    networks:
      - base_network
      -
  application:
    hostname: okami
    ports:
      - "${PORT}:${PORT}"
    restart: always
    build:
      context: .
      dockerfile: "./docker/prod/dockerfile"
    container_name: okami
    networks:
      - base_network
    env_file:
      - .env


networks:
  base_network:


