version: '3.7'


services:
  application:
    network_mode: "host"
    build: 
      context: .
      dockerfile: "./docker/${DOCKERFILE}/dockerfile"
    container_name: okami
    restart: always
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OKAMI_BASE_URL=${OKAMI_BASE_URL}
      - API_PORT=${API_PORT}
      


networks:
  default:
    external:
      name: broker-connection



