services:
  api:
    volumes:
      - ./src/:/app/src
      - ./prisma/schema.prisma/:/app/prisma/schema.prisma
      - ./package.json:/app/package.json
    build:
      context: .
      dockerfile: "./docker/dev/dockerfile"
    container_name: okami
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
