POST {{baseUrl}}/auth/admin-hash-code
Content-Type: application/json
Authorization: Bearer {{sessionToken}}


{
    "hashCodeKey": "RFo6KvVceh72TUHL8d43oKYxTY9ww8EQPGiMFDGkvyZpxCEymCJrFzyit6XF7r6J6DnrF3Jdd3FHzurciGHRgFAEGjbBsvQtbe8u"
}
