FROM node:18-alpine3.16

WORKDIR /apps


COPY  package.json ./
COPY  yarn.lock ./

RUN yarn install
RUN yarn global add pm2

COPY . .

RUN npx prisma generate

RUN yarn build


CMD ["pm2-runtime", "./dist/src/main.js", "--name", "okami"]
