FROM node:18-alpine3.16

WORKDIR /apps
COPY  package.json ./
COPY  yarn.lock ./

ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
NEW_RELIC_LOG=stdout

RUN yarn install
RUN yarn global add pm2

COPY . .

RUN npx prisma generate

RUN yarn build

CMD ["pm2-runtime", "./dist/src/main.js", "--name", "okami"]
