name: "Deploy master"


on:
  push:
    branches:
      - master

jobs:
  validate_tests:
    name: "Validate build and test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup node action"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: "Install dependencies"
        run: |
          yarn install
      - name: "Run tests"
        run: |
          yarn coverage
      - name: "Validate build"
        run: |
          yarn build

  build_and_deploy:
    name: "Build and deploy"
    needs: validate_tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: deploy to cloud
        uses: easingthemes/ssh-deploy@main
        env:
          TARGET: "./apps"
          PORTS: "3000:3000"
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{secrets.HOST}}
          REMOTE_USER: ${{secrets.USERNAME}}
          SCRIPT_AFTER: docker compose -f docker-compose.prd.yml down && docker compose -f docker-compose.prd.yml up --build -d



            
