name: "Deploy master"


on:
  push:
    branches:
      - master

jobs:
  validate_tests:
    name: "Validate build and test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup node action"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: "Install dependencies"
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
      - name: "Run tests"
        run: |
          pnpm run coverage
      - name: "Validate build"
        run: |
          pnpm run build

  build_and_deploy:
    name: "Build and deploy"
    needs: validate_tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: deploy to cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            cd apps/okami
            git pull origin master
            docker compose -f docker-compose.prd.yml up --build -d 
            
