name: "Print coverage by pr"

on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    permissions: write-all
    name: "Print coverage report"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup node action"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: "Install dependencies"
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: "Print coverage"
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          github-token: ${{ secrets.PR_TOKEN }}
