name: "Validate prs"



on:
  pull_request:
    branches:
      - master


jobs:
  validate_tests:
    name: "Validate tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup node action"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: "Install dependencies"
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
      - name: "Run tests"
        run: |
          pnpm run coverage
  coverage:
    name: "Print coverage report"
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup node action"
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            coverage_file: coverage/lcov.info
            comment: true
            comment_title: 'Coverage Report'
            comment_details: 'Coverage report for this PR'
            comment_failure: true
            comment_flags: 'N/A'
            comment_threshold: 80

  validate_build:
    name: "Validate build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup node action"
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: "Install dependencies"
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install
      - name: "Validate build"
        run: |
          pnpm run build
